spring:
  datasource:
    url: jdbc:postgresql://76.155.212.102:5432/postgres
    username: baeldung
    password: baeldung
#    url: jdbc:postgresql://nasally-righteous-dinosaur.data-1.use1.tembo.io:5432/postgres
#    username: postgres
#    password: FoDK1b7X4EMNxulk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: tasktrackr.notifications@gmail.com
    password: jtrbsendpfbphvsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, file:./src/main/resources/static/

frontend:
  url: https://jimby3.github.io/CS3300/

server:
  port: 3000
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat

  http:
    enabled: true
    port: 80
    redirect-port: 3000


logging.level.root: INFO
logging.level.CS3300: INFO




