spring:
  datasource:
#    url: jdbc:postgresql://76.131.177.57:5432/postgres
#    username: baeldung
#    password: baeldung
    url: jdbc:postgresql://menially-live-bellbird.data-1.use1.tembo.io:5432/postgres
    username: postgres
    password: 8RPn2iGmvQhHJgpo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging.level.root: INFO
logging.level.CS3300: INFO