spring:
  datasource:
    url: jdbc:postgresql://76.155.212.102:5432/postgres
    username: baeldung
    password: baeldung
#    url: jdbc:postgresql://nasally-righteous-dinosaur.data-1.use1.tembo.io:5432/postgres
#    username: postgres
#    password: FoDK1b7X4EMNxulk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: tasktrackr.notifications@gmail.com
    password: jtrbsendpfbphvsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, file:./src/main/resources/static/

frontend:
  url: https://jimby3.github.io/CS3300/

server:
  port: 3000  # Set HTTPS port
  ssl:
    enabled: true  # Enable SSL
    key-store: classpath:keystore.jks  # Path to your keystore file
    key-store-password: password  # Keystore password
    key-store-type: JKS  # Keystore type (JKS in this case)
    key-alias: selfsigned  # Alias for the certificate in the keystore
  # Redirect HTTP traffic to HTTPS (Optional)
  http:
    enabled: true
    port: 80  # HTTP port
    redirect-port: 3000  # Redirect HTTP to HTTPS port


logging.level.root: INFO
logging.level.CS3300: INFO




