spring:
  datasource:
    url: jdbc:postgresql://10.0.0.59:5432/postgres
    username: baeldung
    password: baeldung
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging.level.root: INFO
logging.level.CS3300: INFO